version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2726Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: DADA_ExtendedProperty
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/ParmelaDohling579
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_git_2726.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_2726Project
    version: "1.0"
  - name: DADA_ExtendedProperty
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_git_2726.integrations:Test_ExtendedProperty
  packages:
  - name: SIQA_GIT_2726Project
    version: "1.0"
  - name: DADA_ExtendedProperty
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: DADA_ExtendedProperty:maxToStringLength
  packages:
  - name: DADA_ExtendedProperty
    version: "1.0"
- serviceName: project.siqa_git_2726.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_2726Project
    version: "1.0"
  - name: DADA_ExtendedProperty
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.1.0.0.1044
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.1.0.0.1044
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.1.0.0.1044
configurationVariables:
  jdbc.SAP TxStore Pool.maxConns: "10"
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbc.SAP TxStore Pool.poolThreshold: "0"
  jdbc.SAP TxStore Pool.dbURL: jdbc:mysql://adapter-mysql-80-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  jdbc.SAP TxStore Pool.spyenabled: "false"
  jdbc.SAP TxStore Pool.useSSL: "false"
  jdbc.SAP TxStore Pool.waitingThread: "10"
  jdbc.SAP TxStore Pool.description: Connection Pool for the SAP Transaction Store
  jdbc.SAP TxStore Pool.password: "{AES}7EzrljL+N3kbQseeO6Awng=="
  jdbc.SAP TxStore Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP_TxStore_Pool.log;logTName=yes;timestamp=yes)
  jdbc.SAP TxStore Pool.snoopenabled: "false"
  jdbc.SAP TxStore Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP_TxStore_Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.SAP TxStore Pool.expireTime: "60000"
  jdbc.SAP TxStore Pool.minConns: "5"
  jdbc.SAP TxStore Pool.userid: sapuser
  jdbc.SAP TxStore Pool.driverAlias: MySQL CC Driver
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
